Set 3:

•	Find common elements between two arrays [with and without using intersect1d, use isin() instead]

•	Subtract row mean from each row of a 2D array

•	Given a 4×4 array, swap the first half rows with the second half rows

•	Given a 1D array of random numbers, find the indices of the 5 largest values (no sorting/ check argsort() instead).

•	From a 2D NumPy array, extract only the unique rows (no duplicates hint: check unique method).

In [31]:
import numpy as np

• Find common elements between two arrays [with and without using intersect1d, use isin() instead]

In [32]:
arr1 = np.random.randint(1,10,4).reshape(2,2)
arr1

array([[1, 5],
       [5, 9]], dtype=int32)

In [33]:
arr2 = np.random.randint(1,10,4).reshape(2,2)
arr2

array([[2, 3],
       [6, 5]], dtype=int32)

In [34]:
common_ele = np.isin(arr1,arr2)
print('Common Element : ',arr1[common_ele])

Common Element :  [5 5]


In [35]:
common_ele = np.intersect1d(arr1,arr2)
print('Common Element : ',common_ele)

Common Element :  [5]


• Subtract row mean from each row of a 2D array

In [7]:
arr = np.random.randint(1,10,4).reshape(2,2)
arr

array([[7, 4],
       [6, 6]], dtype=int32)

In [8]:
mean_val = np.mean(arr,axis=1,keepdims = True)
mean_val

array([[5.5],
       [6. ]])

In [9]:
arr - mean_val

array([[ 1.5, -1.5],
       [ 0. ,  0. ]])

• Given a 4×4 array, swap the first half rows with the second half rows

In [10]:
arr = np.random.randint(1,25,16).reshape(4,4,)
arr

array([[21, 22,  2,  5],
       [15,  7,  5,  7],
       [14, 22, 13, 23],
       [ 3,  7, 16,  9]], dtype=int32)

In [11]:
half = np.size(arr[0])//2
swaped = np.vstack((arr[half:],arr[:half]))
swaped

array([[14, 22, 13, 23],
       [ 3,  7, 16,  9],
       [21, 22,  2,  5],
       [15,  7,  5,  7]], dtype=int32)

• Given a 1D array of random numbers, find the indices of the 5 largest values (no sorting/ check argsort() instead).

In [12]:
arr = np.random.randint(1,50,10)
arr

array([43, 15, 41,  9, 43,  3, 32,  9, 16, 26], dtype=int32)

In [13]:
np.argsort(arr)[np.size(arr)-5:]

array([9, 6, 2, 4, 0])

• From a 2D NumPy array, extract only the unique rows (no duplicates hint: check unique method).

In [27]:
arr = np.array([[1,2,3],[4,5,6],[1,2,3]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [28]:
unique_rows, counts = np.unique(arr, axis=0, return_counts=True)

In [29]:
unique_only = unique_rows[counts == 1]

In [30]:
unique_only

array([[4, 5, 6]])