Set 2:

•	Normalize a NumPy array [ to normalize means scaling the values of an array into a specific range, often [0, 1]]

•	Create a 5×5 array with 1 on border and 0 inside

•	Create a random array of 10×10: perform stats (min, max, mean, std)

•	Broadcast a 1D array over a 2D array [all possible scenarios]


In [1]:
import numpy as np

• Normalize a NumPy array [ to normalize means scaling the values of an array into a specific range, often [0, 1]]

In [2]:
arr = np.random.randint(1,30,9).reshape(3,3)
arr

array([[ 3, 18, 15],
       [26, 15, 19],
       [16, 28,  5]], dtype=int32)

In [4]:
normalized = (arr - np.min(arr))/(np.max(arr) - np.min(arr))
normalized

array([[0.  , 0.6 , 0.48],
       [0.92, 0.48, 0.64],
       [0.52, 1.  , 0.08]])

• Create a 5×5 array with 1 on border and 0 inside

In [7]:
arr = np.ones((5,5),dtype=int)
arr

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [8]:
arr [1:4,1:4] = 0
arr

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

• Create a random array of 10×10: perform stats (min, max, mean, std)

In [9]:
arr = np.random.randint(1,500,100).reshape(10,10)
arr

array([[421, 333, 232, 368,   9, 294, 131, 473, 100, 156],
       [439,  12, 154, 168, 245,  65, 452, 417, 186, 455],
       [410, 300, 242,  66, 466, 294,   4,  29, 237, 456],
       [228, 295, 227, 253, 486, 335,  55, 323, 450,  35],
       [395,  34, 193, 218,  66, 148, 376, 379, 253, 301],
       [  3, 194, 320, 389,  79, 386,  20, 178, 427, 261],
       [481,   9, 418,  27, 261, 147, 439, 398, 175, 214],
       [426,  96, 341, 355, 410, 131, 119, 282, 115, 418],
       [307, 449,  56,  10, 119, 141, 362, 241, 150,   2],
       [ 90,  88, 408, 176, 457, 108,  12, 160, 203, 330]], dtype=int32)

In [16]:
print(np.min(arr))

2


In [17]:
print(np.max(arr))

486


In [18]:
print(np.mean(arr))

240.52


In [20]:
print(f'{np.std(arr):.2f}')

148.39


• Broadcast a 1D array over a 2D array [all possible scenarios]

In [21]:
arr1 = np.array([5,3,4,2,1])
arr1

array([5, 3, 4, 2, 1])

In [27]:
arr2 = np.random.randint(1,10,5).reshape(5,1)
arr2

array([[9],
       [9],
       [7],
       [5],
       [4]], dtype=int32)

In [28]:
arr1 + arr2

array([[14, 12, 13, 11, 10],
       [14, 12, 13, 11, 10],
       [12, 10, 11,  9,  8],
       [10,  8,  9,  7,  6],
       [ 9,  7,  8,  6,  5]])

In [29]:
arr1 * arr2

array([[45, 27, 36, 18,  9],
       [45, 27, 36, 18,  9],
       [35, 21, 28, 14,  7],
       [25, 15, 20, 10,  5],
       [20, 12, 16,  8,  4]])

In [33]:
arr3 = np.random.randint(1,20,25).reshape(5,5)
arr3

array([[17, 18,  3,  5,  3],
       [ 2, 10,  9,  3,  8],
       [10,  1,  6, 12, 17],
       [11, 14, 18, 13, 11],
       [ 7,  8, 15, 12,  7]], dtype=int32)

In [34]:
arr1 + arr3

array([[22, 21,  7,  7,  4],
       [ 7, 13, 13,  5,  9],
       [15,  4, 10, 14, 18],
       [16, 17, 22, 15, 12],
       [12, 11, 19, 14,  8]])

In [37]:
arr = np.array([1])
arr + arr3

array([[18, 19,  4,  6,  4],
       [ 3, 11, 10,  4,  9],
       [11,  2,  7, 13, 18],
       [12, 15, 19, 14, 12],
       [ 8,  9, 16, 13,  8]])