In [4]:
import numpy as np

In [12]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [13]:
arr.dtype

dtype('int64')

In [14]:
arr.size

6

In [15]:
arr.shape

(6,)

In [20]:
arr1=arr.reshape(2,3)
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
arr2=np.arange(1,13).reshape(3,4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
arr2.astype(float)

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [23]:
zeros=np.zeros([4,4])
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
ones=np.ones([3,3])
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
ran1 = np.random.random([3,4])
ran1

array([[0.69764088, 0.41659399, 0.02539569, 0.1749629 ],
       [0.56337536, 0.45689765, 0.28962857, 0.53211458],
       [0.47285695, 0.59367687, 0.74684749, 0.61212823]])

In [27]:
ran2 = np.random.randint(1,100,16).reshape(4,4)
ran2

array([[34, 63, 18, 81],
       [59, 23, 49,  3],
       [15, 35, 96, 15],
       [ 9, 22, 56, 57]], dtype=int32)

In [28]:
arr3 = np.linspace(-2,20,7)
arr3

array([-2.        ,  1.66666667,  5.33333333,  9.        , 12.66666667,
       16.33333333, 20.        ])

In [29]:
arr4 = np.identity(3)
arr4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
arr5 = np.linspace(1,10,10)
arr5

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])