The main difference between a copy and a view in a NumPy array is data ownership and memory allocation.

In [1]:
import numpy as np

In [11]:
arr = np.array([1,2,7,8,5])
arr

array([1, 2, 7, 8, 5])

copy() -> to make copy on array , don't affect any changes happend in original
-> A copy creates an entirely new array with its own dedicated memory buffer,

In [12]:
x = arr.copy()
x

array([1, 2, 7, 8, 5])

arr[0] = 50   // no reflact copy array when use copy()
arr

In [14]:
x

array([1, 2, 7, 8, 5])

view() -> a view shares the same memory buffer as the original array. any change in original can affect view.

In [15]:
y = arr.view()
y

array([1, 2, 7, 8, 5])

In [20]:
arr[0] = 50
arr

array([50, 60,  7,  8,  5])

In [21]:
y

array([50, 60,  7,  8,  5])

In [22]:
y[1] = 60
y

array([50, 60,  7,  8,  5])

In [23]:
arr

array([50, 60,  7,  8,  5])