In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,3,4,5,2,7])
arr1

array([1, 3, 4, 5, 2, 7])

In [3]:
arr1[3]

np.int64(5)

In [4]:
arr1[-2]

np.int64(2)

In [5]:
arr1[1:5:2]

array([3, 5])

In [7]:
arr1[-4:-1]

array([4, 5, 2])

In [8]:
arr1[:4]

array([1, 3, 4, 5])

In [9]:
arr1[[1,3,5]] #integer indexing

array([3, 5, 7])

In [10]:

arr1[arr1>2]

array([3, 4, 5, 7])

In [11]:
arr1>2

array([False,  True,  True,  True, False,  True])

In [12]:
arr2 = np.random.randint(1,100,16).reshape(4,4)
arr2

array([[77, 41, 64, 14],
       [ 2, 16, 39, 46],
       [93, 98, 65, 39],
       [72, 53, 64, 81]], dtype=int32)

In [13]:
arr2[2]

array([93, 98, 65, 39], dtype=int32)

In [15]:
arr2[2,2]

np.int32(65)

In [16]:
arr2[-2][-2]

np.int32(65)

In [19]:
arr2[1:3,2:4]

array([[39, 46],
       [65, 39]], dtype=int32)

In [21]:
arr2[::2,::2]

array([[77, 64],
       [93, 65]], dtype=int32)

In [22]:
arr2[[0,1,2,3],[0,1,2,3]] #integer slicing

array([77, 16, 65, 81], dtype=int32)

In [24]:
arr2[arr2 % 5 == 0]

array([65], dtype=int32)

In [26]:
arr3 = np.array([
    [
        [1,17,59],
        [21,34,90],
        [12,89,45]
    ],
      [
        [10,37,29],
        [27,27,60],
        [19,80,25]
    ]
])
arr3

array([[[ 1,  7,  9],
        [21, 34, 90],
        [12, 89, 45]],

       [[10, 37, 29],
        [27, 27, 60],
        [19, 80, 25]]])

In [28]:
arr3[1]

array([[10, 37, 29],
       [27, 27, 60],
       [19, 80, 25]])

In [29]:
arr3[0]

array([[ 1,  7,  9],
       [21, 34, 90],
       [12, 89, 45]])

In [30]:
arr3[0][1]

array([21, 34, 90])

In [31]:
arr3[1][0]

array([10, 37, 29])

In [33]:
arr3[1][0][0]

np.int64(10)

In [34]:
arr3[1,2]

array([19, 80, 25])

In [35]:
arr3[0,1]

array([21, 34, 90])

In [36]:
arr3.shape

(2, 3, 3)

In [37]:
arr3.dtype

dtype('int64')

In [38]:
arr3[1,2,2]

np.int64(25)

In [39]:
arr3[::,0:2,1:3]

array([[[ 7,  9],
        [34, 90]],

       [[37, 29],
        [27, 60]]])

In [41]:
i_matrix = [0,0,0,0,1,1,1,1]
i_row = [0,0,2,2,0,0,2,2]
i_cols = [0,2,0,2,0,2,0,2]
arr3[i_matrix,i_row,i_cols]

array([ 1,  9, 12, 45, 10, 29, 19, 25])

In [42]:
arr3[arr3>50]

array([90, 89, 60, 80])