In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,20,16).reshape(4,4)
arr

array([[ 7, 12, 10,  7],
       [10,  3, 10,  5],
       [16, 12, 19,  9],
       [ 9,  6, 19,  2]], dtype=int32)

In [47]:
arr[[0,1,2,3],[3,3,3,3]]

array([7, 5, 9, 2], dtype=int32)

In [45]:
np.sort(arr)

array([[ 7,  7, 10, 12],
       [ 3,  5, 10, 10],
       [ 9, 12, 16, 19],
       [ 2,  6,  9, 19]], dtype=int32)

In [6]:
np.sort(arr, axis = 0)

array([[ 7,  3, 10,  2],
       [ 9,  6, 10,  5],
       [10, 12, 19,  7],
       [16, 12, 19,  9]], dtype=int32)

In [13]:
np.max(arr)

np.int32(19)

In [14]:
np.max(arr,axis=0)

array([16, 12, 19,  9], dtype=int32)

In [15]:
np.min(arr)

np.int32(2)

In [16]:
np.min(arr,axis=0)

array([ 7,  3, 10,  2], dtype=int32)

In [17]:
np.sum(arr)

np.int64(156)

In [19]:
np.sum(arr,axis=0)

array([42, 33, 58, 23])

In [20]:
np.sum(arr,axis=1)

array([36, 28, 56, 36])

In [21]:
np.prod(arr,axis=0)

array([10080,  2592, 36100,   630])

In [22]:
np.prod(arr)

np.int64(594214548480000)

In [23]:
np.prod(arr,axis=1)

array([ 5880,  1500, 32832,  2052])

In [24]:
np.mean(arr)

np.float64(9.75)

In [25]:
np.mean(arr,axis=0)

array([10.5 ,  8.25, 14.5 ,  5.75])

In [26]:
np.mean(arr,axis=1)

array([ 9.,  7., 14.,  9.])

In [27]:
np.median(arr)

np.float64(9.5)

In [28]:
np.median(arr,axis=0)

array([ 9.5,  9. , 14.5,  6. ])

In [29]:
np.median(arr,axis=1)

array([ 8.5,  7.5, 14. ,  7.5])

In [30]:
np.average(arr)

np.float64(9.75)

In [34]:
np.average(arr,axis=0)

array([10.5 ,  8.25, 14.5 ,  5.75])

In [35]:
np.average(arr,axis=1)

array([ 9.,  7., 14.,  9.])

In [31]:
np.std(arr)

np.float64(4.866980583482946)

In [36]:
np.std(arr,axis=0)

array([3.35410197, 3.89711432, 4.5       , 2.58602011])

In [37]:
np.std(arr,axis=1)

array([2.12132034, 3.082207  , 3.80788655, 6.28490254])

In [32]:
np.var(arr)

np.float64(23.6875)

In [33]:
arr1 = np.linspace(2,20,10)
arr1

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [38]:
np.sin(arr1)

array([ 0.90929743, -0.7568025 , -0.2794155 ,  0.98935825, -0.54402111,
       -0.53657292,  0.99060736, -0.28790332, -0.75098725,  0.91294525])

In [39]:
np.tan(arr1)

array([-2.18503986,  1.15782128, -0.29100619, -6.79971146,  0.64836083,
       -0.63585993,  7.24460662,  0.30063224, -1.13731371,  2.23716094])

In [48]:
np.log(arr1)

array([0.69314718, 1.38629436, 1.79175947, 2.07944154, 2.30258509,
       2.48490665, 2.63905733, 2.77258872, 2.89037176, 2.99573227])

In [49]:
np.log(10,arr1)

array([2.30258509, 2.30258509, 2.30258509, 2.30258509, 2.30258509,
       2.30258509, 2.30258509, 2.30258509, 2.30258509, 2.30258509])

In [55]:
np.round(arr)

array([[ 7, 12, 10,  7],
       [10,  3, 10,  5],
       [16, 12, 19,  9],
       [ 9,  6, 19,  2]], dtype=int32)

In [54]:
np.floor(arr)

array([[ 7, 12, 10,  7],
       [10,  3, 10,  5],
       [16, 12, 19,  9],
       [ 9,  6, 19,  2]], dtype=int32)

In [56]:
np.cumsum(arr)

array([  7,  19,  29,  36,  46,  49,  59,  64,  80,  92, 111, 120, 129,
       135, 154, 156])

In [57]:
np.cumsum(arr,axis=0)

array([[ 7, 12, 10,  7],
       [17, 15, 20, 12],
       [33, 27, 39, 21],
       [42, 33, 58, 23]])

In [58]:
np.percentile(arr,50)

np.float64(9.5)

In [59]:
np.percentile(arr,0)

np.float64(2.0)

In [61]:
np.percentile(arr,100)

np.float64(19.0)