In [3]:
import numpy as np

In [8]:
arr = np.random.randint(1,20,16).reshape(4,4)
arr

array([[15,  9,  7, 14],
       [ 1,  4, 17,  9],
       [12,  8,  1,  1],
       [ 4,  3,  3,  6]], dtype=int32)

In [9]:
for i in np.nditer(arr):
    print(i)

15
9
7
14
1
4
17
9
12
8
1
1
4
3
3
6


In [17]:
arr.ravel()

array([15,  9,  7, 14,  1,  4, 17,  9, 12,  8,  1,  1,  4,  3,  3,  6],
      dtype=int32)

In [6]:
arr1 = np.arange(16).reshape(4,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [11]:
np.hstack((arr,arr1))

array([[15,  9,  7, 14,  0,  1,  2,  3],
       [ 1,  4, 17,  9,  4,  5,  6,  7],
       [12,  8,  1,  1,  8,  9, 10, 11],
       [ 4,  3,  3,  6, 12, 13, 14, 15]])

In [12]:
np.vstack((arr,arr1))

array([[15,  9,  7, 14],
       [ 1,  4, 17,  9],
       [12,  8,  1,  1],
       [ 4,  3,  3,  6],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [18]:
arr2 = arr1.ravel()
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [19]:
np.append(arr2,7)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,  7])