In [1]:
import numpy as np

In [6]:
arr = np.array([1,3,6,5,2,7])
arr

array([1, 3, 6, 5, 2, 7])

In [14]:
arr + 5

array([ 6,  8, 11, 10,  7, 12])

In [8]:
arr * 2

array([ 2,  6, 12, 10,  4, 14])

In [12]:
arr % 2

array([1, 1, 0, 1, 0, 1])

In [10]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
arr2 = np.array([10,20,30])
arr2 + arr1

array([[10, 21, 32],
       [13, 24, 35],
       [16, 27, 38]])

In [23]:
arr3 = np.random.randint(1,10,3).reshape(3,1)
arr3

array([[5],
       [8],
       [6]], dtype=int32)

In [24]:
arr2 + arr3

array([[15, 25, 35],
       [18, 28, 38],
       [16, 26, 36]])

In [26]:
arr4 = np.random.randint(1,10,3).reshape(1,3)
arr4

array([[5, 8, 4]], dtype=int32)

In [ ]:
arr1 + arr4

arr4 + arr1

arr5 = np.arange(4).reshape(2,2)
arr5

In [35]:
arr6 = np.arange(6).reshape(3,2,1)
arr6

array([[[0],
        [1]],

       [[2],
        [3]],

       [[4],
        [5]]])

In [42]:
arr7 = np.random.randint(10,25,4).reshape(2,2)
arr7

array([[23, 24],
       [11, 15]], dtype=int32)

In [43]:
arr6 + arr7

array([[[23, 24],
        [12, 16]],

       [[25, 26],
        [14, 18]],

       [[27, 28],
        [16, 20]]])

In [45]:
arr8 = np.arange(4).reshape(2,2)
arr8

array([[0, 1],
       [2, 3]])

In [46]:
arr6 + arr8

array([[[0, 1],
        [3, 4]],

       [[2, 3],
        [5, 6]],

       [[4, 5],
        [7, 8]]])

In [48]:
arr9 = np.random.randint(5,11,6).reshape(2,3)
arr9

array([[ 5, 10,  6],
       [ 8,  6,  7]], dtype=int32)

In [50]:
arr10 = np.random.randint(5,20,8).reshape(2,4)
arr10

array([[ 6, 14,  6,  8],
       [16, 15, 14, 16]], dtype=int32)

arr9 + arr10 // Not Happened

In [53]:
arr11 = np.random.randint(5,20,12).reshape(4,3)
arr11

array([[17,  6, 13],
       [ 6,  6, 19],
       [19, 18, 10],
       [ 9, 12,  6]], dtype=int32)

arr9 + arr11 // Not Happened

In [55]:
def square(n):
    return n*n

squares = np.vectorize(square)
squares(arr8)

array([[0, 1],
       [4, 9]])

In [56]:
arr8

array([[0, 1],
       [2, 3]])